/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    LandingAccessibility: typeof import('./src/components/landing/LandingAccessibility.vue')['default']
    LandingCompetences: typeof import('./src/components/landing/LandingCompetences.vue')['default']
    LandingEtudiantPreview: typeof import('./src/components/landing/LandingEtudiantPreview.vue')['default']
    LandingFaq: typeof import('./src/components/landing/LandingFaq.vue')['default']
    LandingFooter: typeof import('./src/components/landing/LandingFooter.vue')['default']
    LandingHeader: typeof import('./src/components/landing/LandingHeader.vue')['default']
    LandingHero: typeof import('./src/components/landing/LandingHero.vue')['default']
    LandingInitiative: typeof import('./src/components/landing/LandingInitiative.vue')['default']
    LandingMiddleCta: typeof import('./src/components/landing/LandingMiddleCta.vue')['default']
    LandingNewsletter: typeof import('./src/components/landing/LandingNewsletter.vue')['default']
    LandingProcess: typeof import('./src/components/landing/LandingProcess.vue')['default']
    LandingRecommendations: typeof import('./src/components/landing/LandingRecommendations.vue')['default']
    ModuleCard: typeof import('./src/components/ModuleCard.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PreQuizIntro: typeof import('./src/components/PreQuizIntro.vue')['default']
    QuestionRenderer: typeof import('./src/components/quiz/QuestionRenderer.vue')['default']
    QuizResultsPanel: typeof import('./src/components/quiz/QuizResultsPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamSection: typeof import('./src/components/TeamSection.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    ToastContainer: typeof import('./src/components/ToastContainer.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
